### ISSUE TITLE
Provided HA files are not working anymore with recent HA versions

### ISSUE THREAD

**Issue by SR-G** [rasclatt-dot-com/ESP32-Plant-Waterer-for-ESPHome#7]
Just for reference (and in case anyone else would wonder in 2025+) : the various HA YAML files are not copy'n'pastable anymore, as the syntax had changed in the meanwhile.
So on my side, i restarted from scratch, and had to rebuild the rules / configuration manually (which is a tedious process in HA ...).

In case it would be helpful, this is the YAML configuration that i re-did with HA `2025.05`. Notes : 
- compared to this repo, i renamed the files for homogenization/clarity).
- here i kept my *_id for reference (= you can NOT paste logical names, you need real IDs)

**history_stat sensor to add to configuration.yaml** (no real changes, just clarifications about the "-" to be put in place) : 

```yaml
mqtt:
  binary_sensor:
    - name: "plant_water_pump_kitchen_binary_sensor"
      state_topic: "plants/esphome/plant_water_pump_kitchen/switch/water_pump/state"
  sensor:
    - name: "<Another (not related) sensor>"
      state_topic: "<Another topic>"
```

**home_assistant_automation.yaml**

```yaml
alias: When Plant Kitchen is Dry, Activate Pump
description: Waters the kitchen plant when soil is dry
triggers:
  - type: not_moist
    device_id: b8b6015acde9db56dd2b8c07a030f0e4
    entity_id: 0ca3df70efb1aa484d16311a5dbfffc4
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 20
      seconds: 0
conditions:
  - condition: numeric_state
    entity_id: sensor.plant_water_pump_kitchen_watering_triggered_in_4h
    above: "4"
  - condition: device
    type: is_off
    device_id: b8b6015acde9db56dd2b8c07a030f0e4
    entity_id: 20c829d32b3100bea60c57b541334eed
    domain: switch
    for:
      hours: 2
      minutes: 0
      seconds: 0
actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
      flash: short
    target:
      entity_id: light.plant_water_pump_kitchen_fastled_light
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.plant_water_pump_kitchen_water_pump
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.plant_water_pump_kitchen_water_pump
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.plant_water_pump_kitchen_fastled_light
  - action: notify.mobile_app_2311drk48g
    data:
      message: Plant watering automation triggered for kitchen
      title: Watering Triggered
mode: single

```

**home_assistant_alerting_automation.yaml**

```yaml
alias: When Plant Kitchen Has an Issue, Notify and Turn Off Watering
description: ""
triggers:
  - type: not_moist
    device_id: b8b6015acde9db56dd2b8c07a030f0e4
    entity_id: 0ca3df70efb1aa484d16311a5dbfffc4
    domain: binary_sensor
    trigger: device
    for:
      hours: 6
      minutes: 0
      seconds: 0
conditions:
  - condition: numeric_state
    entity_id: sensor.plant_water_pump_kitchen_watering_triggered_in_4h
    below: 4
actions:
  - action: notify.mobile_app_2311drk48g
    metadata: {}
    data:
      message: >-
        Water tank empty or supply tube dislodged - automation disabled as a
        precaution to prevent further water damage or pump damage
      title: Kitchen plant watering alert
  - action: notify.persistent_notification
    metadata: {}
    data:
      title: Kitchen Plant watering alert
      message: >-
        Water tank empty or supply tube dislodged - automation disabled as a
        precaution to prevent further water damage or pump damage
  - action: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      entity_id: automation.waterring_plants_kitchen
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.bureau
      message: >-
        Just letting you know an issue with the plant watering has been
        detected. You need to check if the tank is empty or the water pipe
        is         dislodged. The automation has been disabled as a precaution.
    target:
      entity_id: tts.google_en_com
mode: single
```

**home_assistant_dashboard_setup.yaml**

```yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: switch.plant_water_pump_kitchen_water_pump
      - entity: sensor.plant_water_pump_kitchen_soil_moisture_value
      - entity: sensor.plant_water_pump_kitchen_watering_triggered_in_4h
        name: Number of times triggered in last 4 hours
        secondary_info: last-changed
        icon: mdi:chart-bar
    state_color: true
    title: Plant Watering / Kitchen
  - type: gauge
    entity: sensor.plant_water_pump_kitchen_soil_moisture_value
    name: Soil moisture
    segments:
      - from: 0
        color: "#db4437"
        label: Dry
      - from: 35
        color: "#43a047"
        label: Good
      - from: 55
        color: "#db4437"
        label: Too Wet
    needle: true
```

And just for reference, this is my ESPHOME YAML file (but no real changes here, i think) : 

```yaml
esphome:
  name: plant_water_pump_kitchen

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<your own KEY = the one you'll have to paste in HA during setup>"

ota:
  - platform: esphome
    password: "<your own chosen password for OTA>"

wifi:
  ssid: "<WIFI SSID>"
  password: "<WIFI PASSWORD>"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHOME_Plant_Pump_Kitchen"
    password: "<your own chosen password for AP>"

# Configuration of M5 Atom Lite onboard RGB LED    
light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: 27
    num_leds: 1
    rgb_order: grb
    name: "FastLED Light"

# M5 Atom-Lite Grove port used to connect sensor, pin and sensor 
# calibraation may need updating for other platforms/ sensors
sensor:
  - platform: adc
    pin: 32
    name: Soil Moisture Value
    attenuation: 11db
    id:  soil_moisture
    accuracy_decimals: 0
    unit_of_measurement: "%"
    update_interval: 10s
    icon: mdi:flower
    filters:
      - calibrate_linear:
        - 1.795 -> 0.0
        - 1.53 -> 100.0
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
      - median:
          window_size: 15
          send_every: 7
          send_first_at: 3
 
# This sensor is useful as a trigger for automation in Home Assistant
# change the value of (soil_moisture).state > to desired threshold
# anything below this value will report dry in home assistant.
binary_sensor:
  - platform: template
    name: Soil Moisture
    device_class: moisture
    #Change this value to determine desire wetness of soil
    lambda: |-
        if (id(soil_moisture).state > 35) {
          return true; 
        } else {
          return false; 
        }

# Timed switch for water pump - manually trigger water pump for specified time.
# Ajust delay to suit lenght of time the pump runs
# This was added to prevent the plant/ room getting drenched by an 
# accidental press of the switch emptying a whole water resevoir!
switch:
  - platform: gpio
    pin: 26
    id: relay
    name: "Water pump"
    icon: "mdi:water"
    on_turn_on:
    - logger.log: "Pump Turned On!"
    - delay: 30s
    - switch.turn_off: relay
    - logger.log: "Pump Turned Off!"

# MQTT Setup - esphome defaults to using hostname as prefix, add 
# topic_prefix: if you want something more specific.
# Staatus, sensors, light and switch are published via MQTT

mqtt:
 broker: 192.168.8.XXX
 port: 1883
 topic_prefix: plants/esphome/plant_water_pump_kitchen

captive_portal:
   
```
